# -*- coding: utf-8 -*-
"""Assignmen-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13hIQ-OobbXBn9Yb-bupUbnsiSTp7WC2t
"""

'''1.Write a Python program to print "Hello, World!"'''
print("Hello world")

'''2.Write a Python program that displays your name and age8'''
name = input("enter name : ")
age = int(input("enter age : "))

'''3.Write code to print all the pre-defined keywords in Python using the keyword'''
help("keywords")

'''4.Write a program that checks if a given word is a Python keyword.'''
import keyword

word = input("Enter a word: ")

if keyword.iskeyword(word):
    print(word, "is a Python keyword")
else:
    print(word, "is not a Python keyword")

'''5. Create a list and tuple in Python, and demonstrate how attempting to change an element works differently
for each.'''
my_list = [10, 20, 30]
my_tuple = (10, 20, 30)

my_list[1] = 99
print("List after change:", my_list)

my_tuple[1] = 99
print("Tuple after change:", my_tuple)

'''6. Write a function to demonstrate the behavior of mutable and immutable arguments.'''
def change(a, b):
    a = a + 1        # immutable (int)
    b.append(4)     # mutable (list)

x = 10
y = [1, 2, 3]

change(x, y)

print(x)  # 10 (unchanged)
print(y)  # [1, 2, 3, 4] (changed)

'''7. Write a program that performs basic arithmetic operations on two user-input numbers.'''
a = int(input("enter a : "))
b = int(input("enter b : "))

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

'''8.Write a program to demonstrate the use of logical operators.'''
a = 10
b = 5

print("a > 5 and b > 3:", a > 5 and b > 3)
print("a > 5 or b > 10:", a > 5 or b > 10)
print("not (a > b):", not (a > b))

''' 9. Write a Python program to convert user input from string to integer, float, and boolean types.'''
a = input("enter a : ")
print(type(a))
a = int(a)
print(type(a))
a = float(a)
print(type(a))
a = bool(a)
print(type(a))

'''10. Write code to demonstrate type casting with list elements. '''
list = [1,"2",3.5,True,5]
print(type(list[0]))
print(type(list[1]))
print(type(list[2]))
print(type(list[3]))
print(type(list[4]))

'''11 Write a program that checks if a number is positive, negative, or zero.'''
num = int(input("Enter num: "))

if num < 0:
    print("negative")
elif num > 0:
    print("positive")
else:
    print("zero")

'''12 Write a for loop to print numbers from 1 to 10.'''
for i in range(1,11):
    print(i)

'''13'''
sum_even = 0

for i in range(1, 51):
    if i % 2 == 0:
        sum_even += i

print("Sum of even numbers between 1 and 50:", sum_even)

'''14'''
s = input("Enter a string: ")
reverse = ""
i = len(s) - 1

while i >= 0:
    reverse += s[i]
    i -= 1

print("Reversed string:", reverse)

'''15'''
n = int(input("Enter a number: "))
fact = 1

while n > 0:
    fact *= n
    n -= 1

print("Factorial:", fact)